#!/usr/bin/env bash
#
# GNU/Linux does not really require something like RelativeLink.c
# However, we do want to have the same look and feel with similar features.
#
# Copyright 2017 The Tor Project.  See LICENSE for licensing information.

TOR_BROWSER_WM_CLASS="ZeroNet Browser"
TOR_ALT_NETWORK="zeronet"
TOR_BROWSER_ALT_PROFILE=TorBrowser/Data/Browser/profile.zeronet

./start-hardened-browser "${@}"
